# Use the latest Nginx image
FROM nginx:latest

# Copy the proxy configuration file to the default config directory
COPY proxy.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for the Nginx server
EXPOSE 80
