# Uses the 'latest' Ubuntu, more like 22.04

FROM ubuntu:22.04

# Update APT and upgrade current installed software

RUN apt-get update && apt-get upgrade -y

# Set command to echo 'HeNLo WoRLd!' when the container runs

CMD ["echo", "Hello, World!"]
